apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80        # Service port (External)
      targetPort: 8080 # Pod port
      nodePort: 30007  
  type: NodePort